// Reusable shell for individual blog posts: breadcrumb, hero (eyebrow,
// title, meta, hero phone), prose container, mid-post CTA strip,
// optional FAQ accordion, related-posts grid. Match the visual
// language of the homepage exactly — same THEME, same Phone-style
// device frame, same border radii / shadow vocab.
import type { ReactNode, CSSProperties } from "react";
import { Nav } from "./Nav";
import { Footer } from "./Footer";
import { APP_STORE_URL, THEME } from "./theme";
import type { Post } from "../data/posts";

export interface FAQ {
  q: string;
  a: string;
}

interface Props {
  post: Post;
  /** All other posts, for the related-posts grid. Index passes 3. */
  related: Post[];
  /** Optional FAQ list. Renders an accordion + appears in JSON-LD. */
  faqs?: FAQ[];
  /** Body content; rendered inside the prose container. */
  children: ReactNode;
}

/** Same iPhone-frame component used on the homepage / quick-start
    pages, plus a `<picture>` with a WebP sibling for performance.
    The WebP is generated by `cwebp` next to the PNG (same name, .webp
    extension); browsers without WebP fall back to the PNG. */
function Phone({
  src,
  alt,
  rotate = 0,
  style,
  eager = false,
}: {
  src: string;
  alt: string;
  rotate?: number;
  style?: CSSProperties;
  /** True for the hero image so the LCP fires fast. */
  eager?: boolean;
}) {
  const webp = src.replace(/\.png$/i, ".webp");
  return (
    <div
      style={{
        position: "relative",
        aspectRatio: "1206 / 2622",
        borderRadius: "13% / 6%",
        overflow: "hidden",
        background: "#0E1116",
        padding: "2.4%",
        boxShadow:
          "0 30px 60px -20px rgba(14,82,133,0.35), 0 12px 24px -10px rgba(15,23,42,0.25)",
        transform: `rotate(${rotate}deg)`,
        ...style,
      }}
    >
      <div
        style={{
          width: "100%",
          height: "100%",
          borderRadius: "10% / 4.6%",
          overflow: "hidden",
          background: "#000",
        }}
      >
        <picture>
          <source type="image/webp" srcSet={webp} />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={src}
            alt={alt}
            draggable={false}
            loading={eager ? "eager" : "lazy"}
            fetchPriority={eager ? "high" : "auto"}
            style={{
              display: "block",
              width: "100%",
              height: "100%",
              objectFit: "cover",
              objectPosition: "top",
            }}
          />
        </picture>
      </div>
    </div>
  );
}

export function BlogShell({ post, related, faqs, children }: Props) {
  const dateLabel = new Date(post.date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <>
      <Nav current="blog" />

      <main
        style={{
          background: `linear-gradient(180deg, ${THEME.cloud} 0%, ${THEME.mist} 100%)`,
        }}
      >
        <article
          style={{
            maxWidth: 760,
            margin: "0 auto",
            padding: "48px 24px 64px",
          }}
        >
          {/* Breadcrumb */}
          <nav
            aria-label="Breadcrumb"
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              fontSize: 13,
              color: THEME.muted,
              marginBottom: 24,
              flexWrap: "wrap",
            }}
          >
            <a href="/" style={{ color: THEME.inkSoft, textDecoration: "none", fontWeight: 600 }}>
              Home
            </a>
            <span aria-hidden style={{ color: THEME.subtle }}>›</span>
            <a href="/blog/" style={{ color: THEME.inkSoft, textDecoration: "none", fontWeight: 600 }}>
              Blog
            </a>
            <span aria-hidden style={{ color: THEME.subtle }}>›</span>
            <span style={{ color: THEME.muted, fontWeight: 600 }}>{post.eyebrow}</span>
          </nav>

          {/* Eyebrow */}
          <div
            style={{
              fontSize: 12,
              fontWeight: 800,
              color: THEME.blueDeep,
              letterSpacing: "0.18em",
              textTransform: "uppercase",
              marginBottom: 14,
            }}
          >
            {post.eyebrow}
          </div>

          {/* H1 */}
          <h1
            style={{
              fontSize: "clamp(34px, 5vw, 52px)",
              fontWeight: 900,
              color: THEME.ink,
              letterSpacing: "-0.03em",
              lineHeight: 1.05,
              margin: "0 0 16px",
              textWrap: "balance",
            }}
          >
            {post.title}
          </h1>

          {/* Meta */}
          <p
            style={{
              fontSize: 14,
              color: THEME.inkSoft,
              fontWeight: 500,
              margin: "0 0 32px",
              display: "flex",
              gap: 8,
              flexWrap: "wrap",
            }}
          >
            <time dateTime={post.date}>{dateLabel}</time>
            <span aria-hidden style={{ color: THEME.subtle }}>·</span>
            <span>{post.readTime} min read</span>
          </p>

          {/* Hero phone */}
          {post.heroImage && (
            <figure
              style={{
                margin: "0 0 48px",
                display: "flex",
                justifyContent: "center",
              }}
            >
              <div style={{ width: "min(280px, 70vw)" }}>
                <Phone
                  src={post.heroImage}
                  alt={post.heroImageAlt ?? ""}
                  rotate={-2}
                  eager
                />
              </div>
            </figure>
          )}

          {/* Prose */}
          <div className="lp-prose">{children}</div>

          {/* FAQ */}
          {faqs && faqs.length > 0 && (
            <section style={{ marginTop: 56 }} aria-labelledby="faq-heading">
              <h2
                id="faq-heading"
                style={{
                  fontSize: 24,
                  fontWeight: 900,
                  color: THEME.ink,
                  letterSpacing: "-0.02em",
                  margin: "0 0 16px",
                }}
              >
                Frequently asked questions
              </h2>
              <div style={{ display: "grid", gap: 10 }}>
                {faqs.map((f) => (
                  <details
                    key={f.q}
                    style={{
                      background: "#fff",
                      border: `1px solid ${THEME.hairline}`,
                      borderRadius: 14,
                      padding: "16px 20px",
                    }}
                  >
                    <summary
                      style={{
                        cursor: "pointer",
                        fontWeight: 700,
                        color: THEME.ink,
                        fontSize: 16,
                        listStyle: "none",
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        gap: 16,
                        minHeight: 28,
                      }}
                    >
                      {f.q}
                      <span style={{ color: THEME.blue, fontSize: 22, fontWeight: 800, lineHeight: 1 }}>
                        ＋
                      </span>
                    </summary>
                    <p
                      style={{
                        marginTop: 12,
                        marginBottom: 0,
                        color: THEME.inkSoft,
                        fontSize: 15,
                        lineHeight: 1.65,
                      }}
                    >
                      {f.a}
                    </p>
                  </details>
                ))}
              </div>
            </section>
          )}

          {/* Mid/end CTA */}
          <aside
            style={{
              marginTop: 56,
              borderRadius: 18,
              overflow: "hidden",
              background: `linear-gradient(165deg, ${THEME.near} 0%, #0E2236 60%, #163554 100%)`,
              padding: "28px 28px",
              color: "#fff",
              display: "grid",
              gap: 16,
              alignItems: "center",
              gridTemplateColumns: "auto 1fr auto",
            }}
          >
            <span
              style={{
                width: 48,
                height: 48,
                borderRadius: 12,
                overflow: "hidden",
                background: "#fff",
                flex: "0 0 auto",
              }}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/app-icon-fg.png"
                alt=""
                width={48}
                height={48}
                style={{ display: "block" }}
              />
            </span>
            <div>
              <div
                style={{
                  fontSize: 17,
                  fontWeight: 800,
                  letterSpacing: "-0.01em",
                  marginBottom: 2,
                }}
              >
                Plug it in. See everything.
              </div>
              <div style={{ fontSize: 13, color: "rgba(255,255,255,0.65)" }}>
                Free. Open source. iOS 17+. No accounts.
              </div>
            </div>
            <a
              href={APP_STORE_URL}
              data-cta="post-cta"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 8,
                background: "#fff",
                color: THEME.ink,
                padding: "12px 18px",
                borderRadius: 10,
                fontWeight: 800,
                fontSize: 14,
                textDecoration: "none",
                whiteSpace: "nowrap",
              }}
            >
              <svg width={16} height={16} viewBox="0 0 24 24" fill={THEME.ink} aria-hidden>
                <path d="M16.7 13.3c0-2.6 2.1-3.8 2.2-3.9-1.2-1.8-3.1-2-3.7-2.1-1.6-.2-3.1.9-3.9.9-.8 0-2-.9-3.4-.9-1.7 0-3.4 1-4.3 2.6-1.8 3.2-.5 7.9 1.3 10.4.9 1.3 1.9 2.7 3.3 2.6 1.3-.1 1.8-.9 3.4-.9s2 .9 3.4.8c1.4 0 2.3-1.3 3.2-2.6 1-1.5 1.4-2.9 1.5-3-.1-.1-2.8-1.1-2.8-4.3-.1-2.6 1.7-3.7 1.8-3.7-1-1.5-2.5-1.6-3-1.6Z" />
                <path d="M14.4 5c.8-.9 1.3-2.2 1.2-3.5-1.1.1-2.4.8-3.2 1.6-.7.8-1.4 2-1.2 3.3 1.2.1 2.4-.5 3.2-1.4Z" />
              </svg>
              App Store
            </a>
          </aside>

          {/* Related posts */}
          {related.length > 0 && (
            <section style={{ marginTop: 64 }} aria-labelledby="related-heading">
              <h2
                id="related-heading"
                style={{
                  fontSize: 22,
                  fontWeight: 900,
                  color: THEME.ink,
                  letterSpacing: "-0.02em",
                  margin: "0 0 20px",
                }}
              >
                Keep reading
              </h2>
              <ul
                style={{
                  listStyle: "none",
                  margin: 0,
                  padding: 0,
                  display: "grid",
                  gap: 12,
                  gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
                }}
              >
                {related.map((r) => (
                  <li key={r.slug}>
                    <a
                      href={`/blog/${r.slug}/`}
                      data-internal-to={r.slug}
                      style={{
                        display: "flex",
                        flexDirection: "column",
                        gap: 6,
                        background: "#fff",
                        border: `1px solid ${THEME.hairline}`,
                        borderRadius: 14,
                        padding: "16px 18px",
                        textDecoration: "none",
                        color: THEME.ink,
                        height: "100%",
                      }}
                    >
                      <span
                        style={{
                          fontSize: 11,
                          fontWeight: 800,
                          color: THEME.blueDeep,
                          letterSpacing: "0.16em",
                          textTransform: "uppercase",
                        }}
                      >
                        {r.eyebrow}
                      </span>
                      <span
                        style={{
                          fontSize: 15,
                          fontWeight: 800,
                          letterSpacing: "-0.01em",
                          lineHeight: 1.35,
                        }}
                      >
                        {r.title}
                      </span>
                      <span
                        style={{
                          marginTop: "auto",
                          fontSize: 12,
                          color: THEME.inkSoft,
                          fontWeight: 600,
                        }}
                      >
                        {r.readTime} min read →
                      </span>
                    </a>
                  </li>
                ))}
              </ul>
            </section>
          )}
        </article>
      </main>

      <Footer />

      {/* Scoped prose styles. We deliberately use a global className
          rather than CSS modules because the post bodies are plain JSX
          and we want consistent type scale + link colors without each
          author wiring inline styles per element. */}
      <style>{`
        .lp-prose {
          font-size: 17px;
          line-height: 1.7;
          color: ${THEME.inkSoft};
        }
        .lp-prose h2 {
          font-size: clamp(24px, 3.4vw, 30px);
          font-weight: 900;
          letter-spacing: -0.02em;
          margin: 48px 0 14px;
          color: ${THEME.ink};
          line-height: 1.2;
          text-wrap: balance;
        }
        .lp-prose h3 {
          font-size: 20px;
          font-weight: 800;
          letter-spacing: -0.015em;
          margin: 32px 0 10px;
          color: ${THEME.ink};
        }
        .lp-prose p { margin: 0 0 16px; }
        .lp-prose ul,
        .lp-prose ol {
          margin: 0 0 20px;
          padding-left: 22px;
        }
        .lp-prose li { margin-bottom: 6px; }
        .lp-prose li::marker { color: ${THEME.blue}; }
        .lp-prose a {
          color: ${THEME.blueDeep};
          text-decoration: underline;
          text-underline-offset: 3px;
          text-decoration-thickness: 1.5px;
          font-weight: 600;
        }
        .lp-prose a:hover { color: ${THEME.blueDarker}; }
        .lp-prose strong { color: ${THEME.ink}; font-weight: 700; }
        .lp-prose em { color: ${THEME.ink}; font-style: italic; }
        .lp-prose blockquote {
          margin: 24px 0;
          padding: 16px 20px;
          background: ${THEME.blueWash};
          border-left: 4px solid ${THEME.blue};
          border-radius: 12px;
          color: ${THEME.ink};
        }
        .lp-prose blockquote p:last-child { margin-bottom: 0; }
        .lp-prose code {
          background: ${THEME.blueWash};
          color: ${THEME.blueDeep};
          padding: 2px 6px;
          border-radius: 6px;
          border: 1px solid ${THEME.hairline};
          font-size: 14px;
          font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        }
        .lp-prose table {
          width: 100%;
          border-collapse: collapse;
          margin: 24px 0;
          font-size: 14px;
          background: #fff;
          border-radius: 14px;
          overflow: hidden;
          border: 1px solid ${THEME.hairline};
        }
        .lp-prose thead { background: ${THEME.blueWash}; }
        .lp-prose th {
          text-align: left;
          padding: 12px 14px;
          font-weight: 800;
          color: ${THEME.ink};
          border-bottom: 1px solid ${THEME.hairline};
        }
        .lp-prose td {
          padding: 12px 14px;
          border-bottom: 1px solid ${THEME.hairline};
          color: ${THEME.inkSoft};
          vertical-align: top;
        }
        .lp-prose tr:last-child td { border-bottom: none; }
      `}</style>
    </>
  );
}
